apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: nginx
    release: prometheus
    name: nginx
  name: nginx
  namespace: monitoring
spec:
  endpoints:
  - port: http
    interval: 15s
    path: /nginx_status
    scrapeTimeout: 10s
  selector:
    matchLabels:
      app: nginx