apiVersion: v1
kind: PersistentVolume
metadata:
  name: usb-pv
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem  
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /media/pi/USB32GB

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usb-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
  storageClassName: local-storage